development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: couchpotatoe_dev
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock


production:
  url: <%= ENV['DATABASE_URL'] %>
